model : 'FrostNet'
dataset_name : tiny-imagenet
classes : 200
data_path : '/workspace/host/tiny_imagenet-200/'
save_dir : './saved'

workers: 64
epochs: 1000
batch_size: 256

trainer_options:
  check_val_every_n_epoch: 5

experimental_options:
