gpus: -1 # -1 : use all gpus
save_dir : './saved' # dir for saving log, weights
workers: 4 # number of workers to generate data


batch_size: 32
optimizer: 'sgd'
optimizer_options:
  nesterov: true
  lr: 1e-5
  momentum: 0.9
  weight_decay: 1e-5